START_ROUTES, PRODUCTS_TYPES_STATE = range(2)

ADMIN_START_STATE = 2
ADD_NEW_PRODUCT_TYPE_STATE = 3
(
    ADD_PRODUCT_NAME_STATE,
    ADD_PRODUCT_TYPE_STATE,
    ADD_PRODUCT_PROFITABILITY_STATE,
    ADD_PRODUCT_AGENT_PROFITABILITY_STATE,
    ADD_PRODUCT_PLACEMENT_PERIOD_STATE,
    ADD_PRODUCT_DESCRIPTION_STATE,
    ADD_PRODUCT_FILE_STATE,
) = range(4, 11)


(
    SELECT_PRODUCT_TYPE_FOR_EDIT_PRODUCT_STATE,
    SELECT_PRODUCT_FOR_EDIT_STATE,
    SELECT_PRODUCT_ACTION_STATE,
    EDIT_PRODUCT_NAME_STATE,
    EDIT_PRODUCT_PROFITABILITY_STATE,
    EDIT_PRODUCT_AGENT_PROFITABILITY_STATE,
    EDIT_PRODUCT_PLACEMENT_PERIOD_STATE,
    EDIT_PRODUCT_DESCRIPTION_STATE,
    EDIT_PRODUCT_FILE_PATH_STATE,
) = range(11, 20)
(SELECT_PRODUCT_TYPE_FOR_EDIT_STATE, SELECT_PRODUCT_TYPE_ACTION_STATE, EDIT_PRODUCT_TYPE_NAME_STATE) = range(20, 23)
