"""add readable fields

Revision ID: c6d73ac95136
Revises: ae58908d9a55
Create Date: 2025-11-15 13:12:17.414882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d73ac95136'
down_revision: Union[str, Sequence[str], None] = 'ae58908d9a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('profitability_readable', sa.String(), nullable=True))
    op.add_column('product', sa.Column('agent_profitability_readable', sa.String(), nullable=True))
    op.add_column('product', sa.Column('placement_period_readable', sa.String(), nullable=True))
    op.alter_column('product', 'profitability',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('product', 'agent_profitability',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('product', 'placement_period',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.create_index(op.f('ix_support_dialog_dialog_date'), 'support_dialog', ['dialog_date'], unique=False)
    op.create_index(op.f('ix_support_dialog_user_id'), 'support_dialog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_dialog_user_id'), table_name='support_dialog')
    op.drop_index(op.f('ix_support_dialog_dialog_date'), table_name='support_dialog')
    op.alter_column('product', 'placement_period',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('product', 'agent_profitability',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('product', 'profitability',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_column('product', 'placement_period_readable')
    op.drop_column('product', 'agent_profitability_readable')
    op.drop_column('product', 'profitability_readable')
    # ### end Alembic commands ###
