"""init

Revision ID: 074ab121a4a9
Revises: 
Create Date: 2025-09-26 20:46:40.448566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '074ab121a4a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('create_date', sqlite.DATETIME(), nullable=False),
    sa.Column('update_date', sqlite.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profitability', sa.Integer(), nullable=False),
    sa.Column('agent_profitability', sa.Integer(), nullable=False),
    sa.Column('placement_period', sa.SmallInteger(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('create_date', sqlite.DATETIME(), nullable=False),
    sa.Column('update_date', sqlite.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_product_type_id'), 'product', ['product_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_product_type_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('product_type')
    # ### end Alembic commands ###
